### ISSUE TITLE
Position of the app and the reading time

### ISSUE THREAD

**Issue by shahabsiavash** [CloudflareApps/ReadingTime#1]
Hi,

I think maybe the timing is a little too much. If you calculate the ASCII characters for estimating the time perhaps me having a Persian site that the letters should be Unicode make the app think it is a long text. But I have a 11 minutes for a 5 min max article. 

And I think the counter could be somewhere next to the post like Medium. Or it could have the option for users to decide it should be a floating text or an static element.

Great day and thanks for the apps,

**Comment by GirlBossRush** [comment]
Hi Shahab,

Thanks for reaching out to us. We've recently updated Reading Time to count Unicode characters more accurately. This update also allows the installer to set their words per minute if the default 250 isn't accurate to the site's language.

I've shared your positioning feedback with the team and have included it in our requested feature list. We don't an exact date on if this will be added, but it's on our radar :)

Cheers,
Teffen
